[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
omit = ['tests/*']

per-file-ignores = [
    "__init__.py:F401", # Module imported but unused
]

extend-ignore = [
    "E203", # Whitespace before ":"
    "A002", "A003" # Shadowing python builtin
]
