[default]
    DATABASE_PORT = "5432"
    DATABASE_USER = "postgres"
    DATABASE_PASSWORD = "postgres"
    DATABASE_DB = "nbrb_rates_system"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false

    RABBITMQ_HOST = "localhost"
    RABBITMQ_PORT = "5672"
    RABBITMQ_USERNAME = "username" # placeholders
    RABBITMQ_PASSWORD = "password" # placeholders

    NO_CONFIG_IDLE_TIME = 300

    SMTP_SERVER = ""
    SMTP_PORT = ""
    SMTP_LOGIN = ""
    SMTP_PASSWORD = ""
    USE_SSL = true

    LOG_TO_CONSOLE = true
    LOG_TO_FILE = false
    LOG_TO_SENTRY = false
    JSON_LOGS = false

    CORE_ALIVE_FILE_PATH = "/tmp/core_alive"

    ENABLE_DOCS = true

    PROJECT_NAME = "nbrb_rates_downloader"


[test]
    DATABASE_HOST = "postgres"
    DATABASE_DB = "test_nbrb"

    WEB_LOGIN = "root"
    WEB_PASSWORD = "root"

[development]
    JSON_LOGS = true

[production]
    ENABLE_DOCS = false
    JSON_LOGS = true