"""email model update

Revision ID: 15e3120e762d
Revises: a87d5267cf55
Create Date: 2024-06-25 10:38:45.701752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15e3120e762d"
down_revision: Union[str, None] = "a87d5267cf55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_email_recipients_email"), "email_recipients", ["email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_email_recipients_email"), "email_recipients", type_="unique"
    )
    # ### end Alembic commands ###
