"""request log model

Revision ID: 94a83c6e8690
Revises: 15e3120e762d
Create Date: 2024-06-27 12:51:12.443506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94a83c6e8690"
down_revision: Union[str, None] = "15e3120e762d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint_address", sa.String(), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("requester_ip", sa.String(length=25), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_data", sa.JSON(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_logs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_logs")
    # ### end Alembic commands ###
